// Auto Generated By Script. Do not Change it.
export const STYLE_LIST = [
  'cfm-vertical',
  'game-life',
  'gp-vertical',
  'gp',
  'hlddz',
  'index-horizontal',
  'index-vertical',
  'lolm-lunar',
  'lolm-vertical',
  'lolm',
  'majiang',
  'pvp',
];
