// Auto Generated By Script. Do not Change it.
export const STYLE_LIST = [
  'cf-vertical',
  'game-life-vertical',
  'game-life',
  'gp-vertical',
  'gp',
  'hlddz-vertical',
  'hlddz',
  'index-horizontal',
  'index-vertical',
  'majiang-vertical',
  'majiang',
  'pvp-vertical',
  'pvp',
  'smoba-vertical',
  'smoba',
  'x5m-vertical',
];
