/* Automatically generated by './script/component-config/generate-entry.js' */
import Area from './packages/press-area/press-area.vue';
import AreaIndexBar from './packages/press-area-index-bar/press-area-index-bar.vue';
import AwardPopup from './packages/press-award-popup/press-award-popup.vue';
import LivePlayer from './packages/press-live-player/press-live-player.vue';
import PopupCell from './packages/press-popup-cell/press-popup-cell.vue';
import Protocol from './packages/press-protocol/press-protocol.vue';
import QRCodePopup from './packages/press-q-r-code-popup/press-q-r-code-popup.vue';
import TeamSearch from './packages/press-team-search/press-team-search.vue';
import Turntable from './packages/press-turntable/press-turntable.vue';
import MessageBoard from './packages/press-message-board/press-message-board-list.vue';
import MessageDetail from './packages/press-message-detail/press-message-detail.vue';
import MessageList from './packages/press-message-list/press-message-list.vue';
import ScheduleCard from './packages/press-schedule-card/press-schedule-card.vue';
import ScheduleList from './packages/press-schedule-list/press-schedule-list.vue';
import ScheduleMatchMode from './packages/press-schedule-match-mode/press-schedule-match-mode.vue';
import ScheduleTab from './packages/press-schedule-tab/press-schedule-tab.vue';
import ScheduleTree from './packages/press-schedule-tree/press-schedule-tree.vue';
import HorAwardExplain from './packages/press-hor-award-explain/press-hor-award-explain.vue';
import HorDialog from './packages/press-hor-dialog/press-hor-dialog.vue';
import HorMatchHeader from './packages/press-hor-match-header/press-hor-match-header.vue';
import HorMatchIndex from './packages/press-hor-match-index/press-hor-match-index.vue';
import HorOwnerIndex from './packages/press-hor-owner-index/press-hor-owner-index.vue';
import HorOwnerTheme from './packages/press-hor-owner-theme/press-hor-owner-theme.vue';
import HorRule from './packages/press-hor-rule/press-hor-rule.vue';
import HorScheduleManage from './packages/press-hor-schedule-manage/press-hor-schedule-manage.vue';
import HorSwiperLight from './packages/press-hor-swiper-light/press-hor-swiper-light.vue';
import HorTask from './packages/press-hor-task/press-hor-task.vue';
import LoginAuth from './packages/press-login-auth/press-login-auth.vue';
import LoginBind from './packages/press-login-bind/press-login-bind.vue';
import LoginMobile from './packages/press-login-mobile/press-login-mobile.vue';
import LoginPC from './packages/press-login-p-c/press-login-p-c.vue';
import LoginPCScan from './packages/press-login-p-c-scan/press-login-p-c-scan.vue';
import ActExplainDialog from './packages/press-act-explain-dialog/press-act-explain-dialog.vue';
import ActLaunchDialog from './packages/press-act-launch-dialog/press-act-launch-dialog.vue';
import ActQRCodeDialog from './packages/press-act-q-r-code-dialog/press-act-q-r-code-dialog.vue';
import ActTipDialog from './packages/press-act-tip-dialog/press-act-tip-dialog.vue';
import ActAwardDialog from './packages/press-act-award-dialog/press-act-award-dialog.vue';
import ActBarcodeDialog from './packages/press-act-barcode-dialog/press-act-barcode-dialog.vue';
import ActGetAwardDialog from './packages/press-act-get-award-dialog/press-act-get-award-dialog.vue';
import ActInputAddressDialog from './packages/press-act-input-address-dialog/press-act-input-address-dialog.vue';
import ActInputPhoneDialog from './packages/press-act-input-phone-dialog/press-act-input-phone-dialog.vue';
import ActInputQQ from './packages/press-act-input-q-q/press-act-input-q-q.vue';
import ActModifyPhoneDialog from './packages/press-act-modify-phone-dialog/press-act-modify-phone-dialog.vue';
import ActNotAchievedDialog from './packages/press-act-not-achieved-dialog/press-act-not-achieved-dialog.vue';
import ActPromptDialog from './packages/press-act-prompt-dialog/press-act-prompt-dialog.vue';
import ActSelectAward from './packages/press-act-select-award/press-act-select-award.vue';
import ActGoodsDetailBarcode from './packages/press-act-goods-detail-barcode/press-act-goods-detail-barcode.vue';
import ActGoodsDetailCode from './packages/press-act-goods-detail-code/press-act-goods-detail-code.vue';
import ActGoodsDetailDesc from './packages/press-act-goods-detail-desc/press-act-goods-detail-desc.vue';
import ActGoodsDetailMain from './packages/press-act-goods-detail-main/press-act-goods-detail-main.vue';
import ActGoodsDetailMeta from './packages/press-act-goods-detail-meta/press-act-goods-detail-meta.vue';
import ActGoodsDetailPrimaryButton from './packages/press-act-goods-detail-primary-button/press-act-goods-detail-primary-button.vue';
import ActGoodsDetailQRCode from './packages/press-act-goods-detail-q-r-code/press-act-goods-detail-q-r-code.vue';
import ActGoodsDetailSecondaryButton from './packages/press-act-goods-detail-secondary-button/press-act-goods-detail-secondary-button.vue';
import ActGoodsDetailSelect from './packages/press-act-goods-detail-select/press-act-goods-detail-select.vue';
import ActBenefitItem from './packages/press-act-benefit-item/press-act-benefit-item.vue';
import ActGoodsItem from './packages/press-act-goods-item/press-act-goods-item.vue';
import ActGoodsList from './packages/press-act-goods-list/press-act-goods-list.vue';
import ActGoodsTab from './packages/press-act-goods-tab/press-act-goods-tab.vue';
import ActStoreItem from './packages/press-act-store-item/press-act-store-item.vue';

const components = [
  Area,
  AreaIndexBar,
  AwardPopup,
  LivePlayer,
  PopupCell,
  Protocol,
  QRCodePopup,
  TeamSearch,
  Turntable,
  MessageBoard,
  MessageDetail,
  MessageList,
  ScheduleCard,
  ScheduleList,
  ScheduleMatchMode,
  ScheduleTab,
  ScheduleTree,
  HorAwardExplain,
  HorDialog,
  HorMatchHeader,
  HorMatchIndex,
  HorOwnerIndex,
  HorOwnerTheme,
  HorRule,
  HorScheduleManage,
  HorSwiperLight,
  HorTask,
  LoginAuth,
  LoginBind,
  LoginMobile,
  LoginPC,
  LoginPCScan,
  ActExplainDialog,
  ActLaunchDialog,
  ActQRCodeDialog,
  ActTipDialog,
  ActAwardDialog,
  ActBarcodeDialog,
  ActGetAwardDialog,
  ActInputAddressDialog,
  ActInputPhoneDialog,
  ActInputQQ,
  ActModifyPhoneDialog,
  ActNotAchievedDialog,
  ActPromptDialog,
  ActSelectAward,
  ActGoodsDetailBarcode,
  ActGoodsDetailCode,
  ActGoodsDetailDesc,
  ActGoodsDetailMain,
  ActGoodsDetailMeta,
  ActGoodsDetailPrimaryButton,
  ActGoodsDetailQRCode,
  ActGoodsDetailSecondaryButton,
  ActGoodsDetailSelect,
  ActBenefitItem,
  ActGoodsItem,
  ActGoodsList,
  ActGoodsTab,
  ActStoreItem,
];

const install = function (Vue, opts = {}) {
  components.forEach((component) => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$PRESS = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000,
  };
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ...components,
};
